### ISSUE TITLE
Polish translation (works with 4.0.3)

### ISSUE THREAD

**Issue by dewuer** [downthemall/downthemall#19]
No sure if that's correct way to send it, if not just let me know where I can send the json file, please.
---
```json
{
  "language": {
    "message": "Polski (PL)",
    "description": "Lanuage Name in your language"
  },
  "language_code": {
    "message": "pl",
    "description": "Language code the locale will use, e.g. de or en-GB or pt-BR"
  },
  "add-download": {
    "message": "Dodaj pobieranie",
    "description": "Action for adding a download"
  },
  "add-new": {
    "message": "Dodaj nowe",
    "description": "Button text (adding filters, limits and such)"
  },
  "add-paused-once": {
    "message": "Dodaj wstrzymane tylko tym razem",
    "description": "Checkbox label"
  },
  "add-paused.question": {
    "message": "Czy chcesz zapamiętać tę decyzję i zawsze dodawać nowe pliki wstrzymane od teraz??",
    "description": "Messagebox text"
  },
  "add-paused.title": {
    "message": "Zawsze dodawać wstrzymane?",
    "description": "Title for the add-paused dialog"
  },
  "addpaused": {
    "message": "Dodaj wstrzymane",
    "description": "Action: Add paused"
  },
  "ask-again-later": {
    "message": "Zapytaj mnie później",
    "description": "Button text"
  },
  "batch.batch": {
    "message": "Batch Download",
    "description": "Button text"
  },
  "batch.desc": {
    "message": "Obecny adres URL wydaje się zawierać instrukcje dotyczące pobierania wsadowego.",
    "description": ""
  },
  "batch.items": {
    "message": "Liczba elementów:",
    "description": "Messagebox info text for batch confirmations"
  },
  "batch.preview": {
    "message": "Podgląd:",
    "description": "Messagebox info text for batch confirmations"
  },
  "batch.question": {
    "message": "Czy chcesz dodać to jako wsadowe czy jako pojedyncze pobranie?",
    "description": "Messagebox info text for batch confirmations"
  },
  "batch.single": {
    "message": "Pobieranie pojedyncze",
    "description": "Button text for batch confirmation"
  },
  "batch.title": {
    "message": "Pobieranie wsadowe",
    "description": "Messagebox title for batch confirmations"
  },
  "cancel": {
    "message": "Anuluj",
    "description": "Button text: Cancel"
  },
  "cancel-download": {
    "message": "Anuluj",
    "description": "Action to cancel downloads, e.g. from the context menu"
  },
  "canceled": {
    "message": "Anulowane",
    "description": "Download status text"
  },
  "cannot-be-empty": {
    "message": "To pole nie może być puste",
    "description": "Error message when an input field is empty but has to have a value"
  },
  "change-later-reminder": {
    "message": "Możesz zmienić decyzję później w Ustawieniach",
    "description": "Checkbox label text for decision confirmations"
  },
  "check-selected-items": {
    "message": "Sprawdź wybrane elementy",
    "description": "Menu text"
  },
  "colConnections": {
    "message": "Jednoczesne połączenia",
    "description": "Table column in prefs/network"
  },
  "colDomain": {
    "message": "Domena",
    "description": "Table column in manager"
  },
  "colETA": {
    "message": "Szacowany czas",
    "description": "Table column in manager"
  },
  "colNameURL": {
    "message": "Nazwa/URL",
    "description": "Table column in manager"
  },
  "colPercent": {
    "message": "%",
    "description": "Table column in manager"
  },
  "colProgress": {
    "message": "Postęp",
    "description": "Table column in manager"
  },
  "colSegments": {
    "message": "Segmenty",
    "description": "Table column in manager"
  },
  "colSize": {
    "message": "Rozmiar",
    "description": "Table column in manager"
  },
  "colSpeed": {
    "message": "Prędkość",
    "description": "Table column in manager"
  },
  "conflict-overwrite": {
    "message": "Nadpisz",
    "description": "Option text; prefs/general"
  },
  "conflict-prompt": {
    "message": "Zapytaj",
    "description": "Option text; prefs/general"
  },
  "conflict-rename": {
    "message": "Zmień nazwę",
    "description": "Option text; prefs/general"
  },
  "CRASH": {
    "message": "Błąd wewnętrzny przeglądarki",
    "description": "Error Message"
  },
  "create-filter": {
    "message": "Utwórz filtr",
    "description": "Button text; Create filter dialog; prefs/filters"
  },
  "custom-filename": {
    "message": "Własna nazwa pliku",
    "description": "Label text; single window"
  },
  "deffilter-all": {
    "message": "Wszystkie pliki",
    "description": "Filter label for the All files filter"
  },
  "deffilter-arch": {
    "message": "Archiwa (zip, rar, 7z, …)",
    "description": "Filter label for the Archives filter"
  },
  "deffilter-aud": {
    "message": "Audio (mp3, flac, wav, …)",
    "description": "Filter label for the Audio filter"
  },
  "deffilter-bin": {
    "message": "Oprogramowanie (exe, msi, …)",
    "description": "Filter label for the Software filter"
  },
  "deffilter-doc": {
    "message": "Dokumenty (pdf, odf, docx, …)",
    "description": "Filter label for the Documents filter"
  },
  "deffilter-img": {
    "message": "Obrazy (jpeg, png, gif, …)",
    "description": "Filter label for the Images filter"
  },
  "deffilter-imggif": {
    "message": "Obrazy GIF",
    "description": "Filter label for the GIF filter"
  },
  "deffilter-imgjpg": {
    "message": "Obrazy JPEG",
    "description": "Filter label for the JPEG filter"
  },
  "deffilter-imgpng": {
    "message": "Obrazy PNG",
    "description": "Filter label for the PNG filter"
  },
  "deffilter-vid": {
    "message": "Filmy (mp4, webm, mkv, …)",
    "description": "Filter label for the Videos filter"
  },
  "delete": {
    "message": "Usuń",
    "description": "button text"
  },
  "description": {
    "message": "Opis",
    "description": "Description (keep it short); e.g. the description column in select"
  },
  "disable-other-filters": {
    "message": "Wyłącz inne",
    "description": "Checkbox label. Keep it short"
  },
  "donate": {
    "message": "Wesprzyj!",
    "description": "Donate button"
  },
  "done": {
    "message": "Zrobione",
    "description": "Status text"
  },
  "download": {
    "message": "Pobieranie",
    "description": "Download (noun); e.g. Download column in select"
  },
  "download.verb": {
    "message": "Pobierz",
    "description": "Download (verb/action); e.g. in single and select buttons"
  },
  "dta-regular-all": {
    "message": "DownThemAll! - Wszystkie zakładki",
    "description": "Menu text"
  },
  "dta-turbo-all": {
    "message": "OneClick! - Wszystkie zakładki",
    "description": "Menu text"
  },
  "dta.regular": {
    "message": "DownThemAll!",
    "description": "Regular dta action; Menu text"
  },
  "dta.regular.image": {
    "message": "Zapisz Obraz z DownThemAll!",
    "description": "Menu text"
  },
  "dta.regular.link": {
    "message": "Zapisz Link z DownThemAll!",
    "description": "Menu text"
  },
  "dta.regular.media": {
    "message": "Zapisz Media z DownThemAll!",
    "description": "Menu text"
  },
  "dta.regular.selection": {
    "message": "Zapisz wybór z DownThemAll!",
    "description": "Menu text"
  },
  "dta.turbo": {
    "message": "OneClick!",
    "description": "OneClick! action; Menu text"
  },
  "dta.turbo.image": {
    "message": "Zapisz Obraz z One Click!",
    "description": "Menu text"
  },
  "dta.turbo.link": {
    "message": "Zapisz Link z One Click!",
    "description": "Menu text"
  },
  "dta.turbo.media": {
    "message": "Zapisz Media z One Click!",
    "description": "Menu text"
  },
  "dta.turbo.selection": {
    "message": "Zapisz wybór z One Click!",
    "description": "Menu text"
  },
  "error.invalidMask": {
    "message": "Nieprawidłowa maska zmiany nazwy",
    "description": "Error message; single/select window"
  },
  "error.invalidReferrer": {
    "message": "Nieprawidłowy odnośnik",
    "description": "Error message; single window"
  },
  "error.invalidURL": {
    "message": "Nieprawidłowy URL",
    "description": "Error message; single window"
  },
  "error.noItemsSelected": {
    "message": "Nie wybrano żadnych elementów",
    "description": "Error Message; select window"
  },
  "extensionDescription": {
    "message": "Mass Downloader do Twojej przeglądarki",
    "description": "DownThemAll! tagline, displayed in about:addons; Please do NOT refer to a specific browser such as firefox, as we will probably support more than one"
  },
  "fastfilter.placeholder": {
    "message": "Wyrażenie wieloznaczne lub wyrażenie regularne",
    "description": "Placeholder for fastfilter inputs"
  },
  "fastfiltering": {
    "message": "Szybkie filtrowanie",
    "description": "Label for Fast Filtering input"
  },
  "FILE_FAILED": {
    "message": "Błąd dostępu do pliku",
    "description": "Error Message"
  },
  "filter-at-least-one": {
    "message": "Musisz wybrać co najmniej jeden typ filtru!",
    "description": "Error message when no filter types are selected for a filter in the preferences UI"
  },
  "filter-create.title": {
    "message": "Utwórz nowy filtr",
    "description": "Message box title"
  },
  "filter-expression": {
    "message": "Filter-Wyrażenie",
    "description": "Message box label"
  },
  "filter-label": {
    "message": "Filtr-Nazwa",
    "description": "Message box label"
  },
  "filter-type-link": {
    "message": "Link Filter",
    "description": "Message box checkbox label"
  },
  "filter-type-media": {
    "message": "Media Filter",
    "description": "Message box checkbox label"
  },
  "filter-types": {
    "message": "Filtr-Typy",
    "description": "Message box label"
  },
  "finishing": {
    "message": "Kończenie",
    "description": "Status text"
  },
  "force-start": {
    "message": "Wymuś Start",
    "description": "Menu text"
  },
  "information.title": {
    "message": "Informacja",
    "description": "Used in message boxes"
  },
  "invalid-domain-pref": {
    "message": "Nieprawidłowa domena",
    "description": "Error message in prefs/network"
  },
  "invert-selection": {
    "message": "Odwróć zaznaczenie",
    "description": "Menu text"
  },
  "key-alt": {
    "message": "Alt",
    "description": "Short for Alt-Key"
  },
  "key-ctrl": {
    "message": "Ctrl",
    "description": "Short for Ctrl-Key"
  },
  "key-delete": {
    "message": "Del",
    "description": "Short for Delete-key"
  },
  "key-end": {
    "message": "End",
    "description": "Short for End-key"
  },
  "key-home": {
    "message": "Home",
    "description": "Short for home key"
  },
  "key-pagedown": {
    "message": "PageDown",
    "description": "Short for pagedown-key"
  },
  "key-pageup": {
    "message": "PageUp",
    "description": "Short for PageUp-key"
  },
  "limited-to": {
    "message": "Ograniczone do",
    "description": "Label text; used in prefs/network"
  },
  "links": {
    "message": "Linki",
    "description": "Links tab label (short); select window"
  },
  "manager-status-items": {
    "message": "Ukończono $COMPLETE$ z $TOTAL$ pobierań ($SHOWING$ wyświetlono), $RUNNING$ trwających",
    "description": "Status bar text; manager",
    "placeholders": {
      "complete": {
        "content": "$1",
        "example": "10"
      },
      "running": {
        "content": "$4",
        "example": "4"
      },
      "showing": {
        "content": "$3",
        "example": "90"
      },
      "total": {
        "content": "$2",
        "example": "100"
      }
    }
  },
  "manager.short": {
    "message": "Menedżer",
    "description": "Menu text"
  },
  "manager.title": {
    "message": "Menedżer DownThemAll!",
    "description": "Window/tab title"
  },
  "mask": {
    "message": "Maska",
    "description": "Renaming mask (short); used in e.g. select"
  },
  "mask.default": {
    "message": "Domyślna Maska",
    "description": "Status text; Used in the mask column, select window"
  },
  "media": {
    "message": "Media",
    "description": "Media label (short)"
  },
  "missing": {
    "message": "Brakujące",
    "description": "Status text in manager"
  },
  "move-bottom": {
    "message": "Dół",
    "description": "Action for moving a download to the bottom"
  },
  "move-down": {
    "message": "Niżej",
    "description": "Action for moving a download down"
  },
  "move-top": {
    "message": "Góra",
    "description": "Action for moving a download to the top"
  },
  "move-up": {
    "message": "Wyżej",
    "description": "Action for moving a download up"
  },
  "nagging-message": {
    "message": "Dodałeś do tej pory $DOWNLOADS$ pobrań z DownThemAll! Jako stały użytkownik możesz rozważyć darowiznę na wsparcie dalszego rozwoju. Dzięki!",
    "description": "Donation nagging message; displayed as a notification bar in manager",
    "placeholders": {
      "downloads": {
        "content": "$1",
        "example": ""
      }
    }
  },
  "NETWORK_FAILED": {
    "message": "Błąd sieci",
    "description": "Error Message"
  },
  "never-ask-again": {
    "message": "Nie pytaj ponownie",
    "description": "Donation button"
  },
  "no-links": {
    "message": "Nie znaleziono linków!",
    "description": "Notification text"
  },
  "noitems.label": {
    "message": "Nie wybrano elementów",
    "description": "Status bar text in select"
  },
  "numitems.label": {
    "message": "$ITEMS$ elementów wybrano…",
    "description": "Status bar text in select; Number of items selected (label)",
    "placeholders": {
      "items": {
        "content": "$1",
        "example": "1000"
      }
    }
  },
  "ok": {
    "message": "OK",
    "description": "Button text; Used in message boxes"
  },
  "open-directory": {
    "message": "Otwórz folder",
    "description": "Menu text; manager context"
  },
  "open-file": {
    "message": "Otwórz plik",
    "description": "Menu text; manager context"
  },
  "open-link": {
    "message": "Otwórz Link",
    "description": "Menu text; select window"
  },
  "options-filters": {
    "message": "Filtry",
    "description": "Pref tab text"
  },
  "options-general": {
    "message": "Ogólne",
    "description": "Pref tab text"
  },
  "options-network": {
    "message": "Sieć",
    "description": "Pref tab text"
  },
  "pause-download": {
    "message": "Pauza",
    "description": "Action for pausing a download"
  },
  "paused": {
    "message": "Wstrzymane",
    "description": "Status text; manager"
  },
  "pref-add-paused": {
    "message": "Dodaj nowe pobierania wstrzymane, zamiast rozpoczynać je natychmiast",
    "description": "Preferences/General"
  },
  "pref-concurrent-downloads": {
    "message": "Jednoczesne pobierania",
    "description": "Preferences/Network"
  },
  "pref-finish-notification": {
    "message": "Pokaż powiadomienie, gdy kolejka zakończy pobieranie",
    "description": "Preferences/General"
  },
  "pref-global-turbo": {
    "message": "Przycisk przeglądarki powinien być OneClick!",
    "description": "Preferences/General"
  },
  "pref-hide-context": {
    "message": "Nie pokazuj ogólnych pozycji menu kontekstowego",
    "description": "Preferences/General"
  },
  "pref-manager-tooltip": {
    "message": "Pokaż podpowiedzi w zakładkach Menedżera",
    "description": "Preferences/General"
  },
  "pref-open-manager-on-queue": {
    "message": "Otwórz zakładkę Menedżera po zakolejkowaniu niektórych pobrań",
    "description": "Preferences/General"
  },
  "pref-queue-notification": {
    "message": "Pokaż powiadomienie, gdy kolejkujesz nowe pobieranie",
    "description": "Preferences/General"
  },
  "pref-remove-missing-on-init": {
    "message": "Usuwaj brakujące pobrania po restarcie",
    "description": "Preferences/General"
  },
  "pref-show-urls": {
    "message": "Pokaż URL zamiast Nazw",
    "description": "Preferences/General"
  },
  "pref-text-links": {
    "message": "Spróbuj znaleźć linki w treści strony internetowej (wolniejsze)",
    "description": "Preferences/General"
  },
  "pref.manager": {
    "message": "Menedżer",
    "description": "Preferences/General; group text"
  },
  "pref.netglobal": {
    "message": "Globalne Ograniczenia Sieci",
    "description": "Preferences/General; group text"
  },
  "pref.queueing": {
    "message": "Kolejkowanie Pobrań",
    "description": "Preferences/General; group text"
  },
  "pref.ui": {
    "message": "Interfejs Użytkownika",
    "description": "Preferences/General; group text"
  },
  "prefs.conflicts": {
    "message": "Kiedy plik istnieje",
    "description": "Preferences/General; group text"
  },
  "prefs.short": {
    "message": "Ustawienia",
    "description": "Menu text; Preferences"
  },
  "prefs.title": {
    "message": "DownThemAll! Preferences",
    "description": "Window/tab title; Preferences"
  },
  "queue-finished": {
    "message": "Kolejka pobierania została zakończona",
    "description": "Notification text"
  },
  "queued": {
    "message": "Zakolejkowane",
    "description": "Status text"
  },
  "queued-download": {
    "message": "Zakolejkowane 1 pobieranie!",
    "description": "Notification text; single download"
  },
  "queued-downloads": {
    "message": "Zakolejkowane $COUNT$ pobierań!",
    "description": "Notification text; multiple downloads",
    "placeholders": {
      "count": {
        "content": "$1",
        "example": "100"
      }
    }
  },
  "referrer": {
    "message": "Odnośnik",
    "description": "Label for \"Referrer\""
  },
  "remember": {
    "message": "Zapamiętaj tę decyzję",
    "description": "Checkbox text for confirmation, e.g. when removing a download in manager"
  },
  "remove-all-complete-downloads": {
    "message": "Usuń wszystkie zakończone",
    "description": "Menu text"
  },
  "remove-all-downloads": {
    "message": "Usuń wszystkie",
    "description": "Menu text"
  },
  "remove-all-downloads.question": {
    "message": "Czy chcesz usunąć WSZYSTKIE pobierania?",
    "description": "Messagebox text"
  },
  "remove-batch-downloads": {
    "message": "Usuń Obecny Wsad",
    "description": "Menu text"
  },
  "remove-batch-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie pobrania z tego samego wsadu, co aktualnie wybrane pobieranie?",
    "description": "Messagebox text"
  },
  "remove-complete-downloads": {
    "message": "Usuń Zakończone Pobierania",
    "description": "Action for removing complete downloads"
  },
  "remove-complete-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie zakończone pobierania?",
    "description": "Messagebox text"
  },
  "remove-complete-filter-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie zakończone pobrania odpowiadające filtrowi '$FILTER$'",
    "description": "Messagebox text",
    "placeholders": {
      "filter": {
        "content": "$1",
        "example": "JPEG Images"
      }
    }
  },
  "remove-complete-selection-downloads.question": {
    "message": "Do you want to remove all complete downloads in the current selection?",
    "description": "Messagebox text"
  },
  "remove-domain-complete-downloads": {
    "message": "Usuń zakończone z obecnej domeny",
    "description": "Menu text"
  },
  "remove-domain-complete-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie zakończone pobrania z domeny '$DOMAIN$'?",
    "description": "Messagebox text",
    "placeholders": {
      "domain": {
        "content": "$1",
        "example": "example.org"
      }
    }
  },
  "remove-domain-downloads": {
    "message": "Usuń obecną domenę",
    "description": "Menu text"
  },
  "remove-domain-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie pobrania z domeny '$DOMAIN$'?",
    "description": "Messagebox text",
    "placeholders": {
      "domain": {
        "content": "$1",
        "example": "example.org"
      }
    }
  },
  "remove-download": {
    "message": "Usuń Pobranie",
    "description": "Action for removing a download, no matter what state"
  },
  "remove-download.question": {
    "message": "Czy chcesz usunąć wybrane pliki do pobrania?",
    "description": "Messagebox text"
  },
  "remove-downloads": {
    "message": "Usuń pobierania",
    "description": "Menu text"
  },
  "remove-downloads.title": {
    "message": "Czy na pewno chcesz usunąć pobrane pliki?",
    "description": "Messagebox title; manager"
  },
  "remove-failed-downloads": {
    "message": "Usuń błędne",
    "description": "Menu text"
  },
  "remove-failed-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie nieudane pobrania?",
    "description": "Messagebox text"
  },
  "remove-filter-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie pobrania pasujące do filtra '$FILTER$'?",
    "description": "Mesagebox text",
    "placeholders": {
      "filter": {
        "content": "$1",
        "example": "JPEG Images"
      }
    }
  },
  "remove-missing": {
    "message": "Wyczyść Brakujące Pobrania",
    "description": "Menu text"
  },
  "remove-missing-downloads.question": {
    "message": "Czy chcesz wyczyścić wszystkie brakujące pobrania?",
    "description": "Messagebox text"
  },
  "remove-paused-downloads": {
    "message": "Usuń wstrzymane",
    "description": "Menu text"
  },
  "remove-paused-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie wstrzymane pobrania?",
    "description": "Messagebox text"
  },
  "remove-selected-complete-downloads": {
    "message": "Usuń ukończone z zaznaczonych",
    "description": "Menu text"
  },
  "remove-selected-complete-downloads.question": {
    "message": "Czy chcesz usunąć wszystkie zakończone pobrania z bieżącego wyboru?",
    "description": "Messagebox text"
  },
  "remove-selected-downloads": {
    "message": "Usuń wybrane",
    "description": "Menu text"
  },
  "rename": {
    "message": "Zmień nazwę",
    "description": "UI for renaming; currently unused"
  },
  "renamer-batch": {
    "message": "Numer Wsadu",
    "description": "Mask text; see mask button"
  },
  "renamer-d": {
    "message": "Date Added Day",
    "description": "Mask text; see mask button"
  },
  "renamer-date": {
    "message": "Data dodania",
    "description": "Mask text; see mask button"
  },
  "renamer-domain": {
    "message": "Nazwa Domeny (TLD)",
    "description": "Mask text; see mask button"
  },
  "renamer-ext": {
    "message": "Rozszerzenie pliku",
    "description": "Mask text; see mask button"
  },
  "renamer-hh": {
    "message": "Date Added Hour",
    "description": "Mask text; see mask button"
  },
  "renamer-host": {
    "message": "Nazwa hosta",
    "description": "Mask text; see mask button"
  },
  "renamer-idx": {
    "message": "Numer elementu we Wsadzie",
    "description": "Mask text; see mask button"
  },
  "renamer-info": {
    "message": "Adding 'flat', such as *flatsubdirs* will replace all slashes in the value, thus not creating directories",
    "description": "Mask text; see mask button; do NOT translate any mentions of \"flat\"!"
  },
  "renamer-m": {
    "message": "Date Added Month",
    "description": "Mask text; see mask button"
  },
  "renamer-mm": {
    "message": "Date Added Minute",
    "description": "Mask text; see mask button"
  },
  "renamer-name": {
    "message": "Nazwa pliku",
    "description": "Mask text; see mask button"
  },
  "renamer-num": {
    "message": "Alias dla *Wsadu*",
    "description": "Mask text; see mask button"
  },
  "renamer-qstring": {
    "message": "Ciąg zapytania",
    "description": "Mask text; see mask button"
  },
  "renamer-ref": {
    "message": "Odnośnik",
    "description": "Mask text; see mask button"
  },
  "renamer-refdomain": {
    "message": "Referrer Domain Name (TLD)",
    "description": "Mask text; see mask button"
  },
  "renamer-refext": {
    "message": "Referrer File Extension",
    "description": "Mask text; see mask button"
  },
  "renamer-refhost": {
    "message": "Referrer Host Name",
    "description": "Mask text; see mask button"
  },
  "renamer-refname": {
    "message": "Referrer File Name",
    "description": "Mask text; see mask button"
  },
  "renamer-refqstring": {
    "message": "Referrer Query String",
    "description": "Mask text; see mask button"
  },
  "renamer-refsubdirs": {
    "message": "Referrer Path",
    "description": "Mask text; see mask button"
  },
  "renamer-refurl": {
    "message": "Referrer URL (without protocol)",
    "description": "Mask text; see mask button"
  },
  "renamer-ss": {
    "message": "Date Added Second",
    "description": "Mask text; see mask button"
  },
  "renamer-subdirs": {
    "message": "Ścieżka",
    "description": "Mask text; see mask button"
  },
  "renamer-tags": {
    "message": "Renaming Mask Tags",
    "description": "Mask text; see mask button"
  },
  "renamer-text": {
    "message": "Opis",
    "description": "Mask text; see mask button"
  },
  "renamer-title": {
    "message": "Tytuł",
    "description": "Mask text; see mask button"
  },
  "renamer-url": {
    "message": "URL (bez protokołu)",
    "description": "Mask text; see mask button"
  },
  "renamer-y": {
    "message": "Date Added Year",
    "description": "Mask text; see mask button"
  },
  "renmask": {
    "message": "Renaming mask",
    "description": "Renaming mask (long)"
  },
  "reset": {
    "message": "Reset",
    "description": "Button text; pref window"
  },
  "reset-confirmations": {
    "message": "Zresetuj zapamiętane potwierdzenia",
    "description": "Button text; pref/General"
  },
  "reset-confirmations.done": {
    "message": "Wszystkie wcześniej zapamiętane potwierdzenia zostały zresetowane!",
    "description": "Messagebox text; pref/General"
  },
  "reset-layouts": {
    "message": "Zresetuj ustawienia interfejsu użytkownika",
    "description": "Button text; pref/General"
  },
  "reset-layouts.done": {
    "message": "Wszystkie wcześniej zapamiętane dostosowania układu zostały zresetowane! Może być konieczne ponowne załadowanie okien/kart.",
    "description": "Messagebox text; pref/General"
  },
  "resume-download": {
    "message": "Wznów",
    "description": "Action for resuming a download"
  },
  "running": {
    "message": "Trwające",
    "description": "Status text"
  },
  "save": {
    "message": "Zapisz",
    "description": "Button text; e.g. prefs/Network"
  },
  "search": {
    "message": "Szukaj…",
    "description": "Placeholder text; manager status search field"
  },
  "select-all": {
    "message": "Wybierz wszystko",
    "description": "Menu text; e.g. select context"
  },
  "select-checked": {
    "message": "Wybierz Zaznaczone",
    "description": "Menu text; select context"
  },
  "select-none": {
    "message": "Odznacz",
    "description": "Menu text; select context"
  },
  "select.title": {
    "message": "DownThemAll! - Select your Downloads",
    "description": "Title of the select window"
  },
  "SERVER_BAD_CONTENT": {
    "message": "Nie znaleziono",
    "description": "Error message"
  },
  "SERVER_FAILED": {
    "message": "Błąd serwera",
    "description": "Error message"
  },
  "SERVER_FORBIDDEN": {
    "message": "Zabronione",
    "description": "Error message"
  },
  "SERVER_UNAUTHORIZED": {
    "message": "Nieautoryzowany",
    "description": "Error message"
  },
  "set-mask": {
    "message": "Set Renaming Mask",
    "description": "Menu text; select window"
  },
  "single.batchexamples": {
    "message": "Wsady są wspierane, np.:",
    "description": "Header text; single window"
  },
  "single.header": {
    "message": "Wprowadź URL pobierania (link) i inne opcje",
    "description": "Header text; single window"
  },
  "single.title": {
    "message": "DownThemAll! - Dodaj link",
    "description": "Title of single window"
  },
  "size-progress": {
    "message": "$WRITTEN$ z $TOTAL$",
    "description": "Status text; manager size column",
    "placeholders": {
      "total": {
        "content": "$2",
        "example": ""
      },
      "written": {
        "content": "$1",
        "example": ""
      }
    }
  },
  "size-unknown": {
    "message": "Nieznany",
    "description": "Status text; manager size column"
  },
  "sizeB": {
    "message": "$S$B",
    "description": "Size formatting; bytes",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100b"
      }
    }
  },
  "sizeGB": {
    "message": "$S$GB",
    "description": "Size formatting; giga bytes",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.200GB"
      }
    }
  },
  "sizeKB": {
    "message": "$S$KB",
    "description": "Size formatting; kilo bytes",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.2KB"
      }
    }
  },
  "sizeMB": {
    "message": "$S$MB",
    "description": "Size formatting; mega bytes",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.22MB"
      }
    }
  },
  "sizePB": {
    "message": "$S$PB",
    "description": "Size formatting; peta bytes (you never know)",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.212PB"
      }
    }
  },
  "sizes-huge": {
    "message": "Wielki (> $HIGH$)",
    "description": "Menu text; manager size column dropdown",
    "placeholders": {
      "high": {
        "content": "$1",
        "example": "1GB"
      }
    }
  },
  "sizes-large": {
    "message": "Duży ($LOW$ - $HIGH$)",
    "description": "Menu text; manager size column dropdown",
    "placeholders": {
      "high": {
        "content": "$2",
        "example": "10MB"
      },
      "low": {
        "content": "$1",
        "example": "1MB"
      }
    }
  },
  "sizes-medium": {
    "message": "Średni ($LOW$ - $HIGH$)",
    "description": "Menu text; manager size column dropdown",
    "placeholders": {
      "high": {
        "content": "$2",
        "example": "10MB"
      },
      "low": {
        "content": "$1",
        "example": "1MB"
      }
    }
  },
  "sizes-small": {
    "message": "Mały ($LOW$ - $HIGH$)",
    "description": "Menu text; manager size column dropdown",
    "placeholders": {
      "high": {
        "content": "$2",
        "example": "10MB"
      },
      "low": {
        "content": "$1",
        "example": "1MB"
      }
    }
  },
  "sizeTB": {
    "message": "$S$TB",
    "description": "Size formatting; tera bytes (you never know)",
    "placeholders": {
      "s": {
        "content": "$1",
        "example": "100.002TB"
      }
    }
  },
  "speedB": {
    "message": "$SPEED$b/s",
    "description": "Speed formatting; bytes",
    "placeholders": {
      "speed": {
        "content": "$1",
        "example": "100b/s"
      }
    }
  },
  "speedKB": {
    "message": "$SPEED$KB/s",
    "description": "Speed formatting; kilo bytes",
    "placeholders": {
      "speed": {
        "content": "$1",
        "example": "100.1KB/s"
      }
    }
  },
  "speedMB": {
    "message": "$SPEED$MB/s",
    "description": "Speed formatting; mega bytes",
    "placeholders": {
      "speed": {
        "content": "$1",
        "example": "100.20MB/s"
      }
    }
  },
  "statusNetwork-active.title": {
    "message": "Nowe pobrania zostaną uruchomione",
    "description": "Status bar tooltip; manager network icon"
  },
  "statusNetwork-inactive.title": {
    "message": "Nowe pobrania nie zostaną uruchomione",
    "description": "Status bar tooltip; manager network icon"
  },
  "title": {
    "message": "Tytuł",
    "description": "Column text; Title label (short)"
  },
  "toggle-selected-items": {
    "message": "Toggle Check for Selected Items",
    "description": "Menu text; select"
  },
  "tooltip-date": {
    "message": "Data dodania:",
    "description": "Tooltip text; manager/downloads"
  },
  "tooltip-eta": {
    "message": "Pozostało:",
    "description": "Tooltip text; manager/downloads; Time"
  },
  "tooltip-from": {
    "message": "Od:",
    "description": "Tooltip text; manager/downloads; source URL"
  },
  "tooltip-size": {
    "message": "Rozmiar:",
    "description": "Tooltip text; manager/downloads"
  },
  "tooltip-speed-average": {
    "message": "Średnio:",
    "description": "Tooltip text; manager/downloads"
  },
  "tooltip-speed-current": {
    "message": "Obecnie:",
    "description": "Tooltip text; manager/downloads"
  },
  "uncheck-selected-items": {
    "message": "Odznacz wybrane elementy",
    "description": "Menu text; select"
  },
  "unlimited": {
    "message": "Nielimitowane",
    "description": "Option text; Prefs/Network"
  },
  "useonlyonce": {
    "message": "Użyj raz",
    "description": "Label for Use-Once checkboxes"
  }
}
```

[messages.zip](https://github.com/downthemall/downthemall/files/3549489/messages.zip)

**Comment by nmaier** [comment]
I see there are some untranslated strings in there, like:
```
    "message": "Set Renaming Mask",
    "message": "Do you want to remove all complete downloads in the current selection?",
```

It would be best to translate those. Or at least remove them. If they are removed, the English text will be used by DownThemAll! automatically.

**Comment by dewuer** [comment]
All right, I finished the missing translations, but just to let you know - https://downthemall.github.io/translate/ was showing 100% finished translation when I loaded  the file.
Anyway, now it is fully translated.

Oh, btw, part of the settings window is not changing to Polish even the translation is done.
I am talking about "_When a file exists_"; "_Overwrite_"; "_Rename_".

Also in Manager when you press plus button to add new download the names of the fields are also in original language - "_Title_"; "_Mask_", etc.

File for PL attached in zip.
[messages.zip](https://github.com/downthemall/downthemall/files/3554188/messages.zip)

**Comment by nmaier** [comment]
>All right, I finished the missing translations, but just to let you know - https://downthemall.github.io/translate/ was showing 100% finished translation when I loaded the file.

Well, it doesn't check if the "translated" strings are the same as the English ones. Because sometimes that's appropriate. I should add a tracker displaying how many strings are unchanged from English...

**Comment by nmaier** [comment]
>Oh, btw, part of the settings window is not changing to Polish even the translation is done.
I am talking about "When a file exists"; "Overwrite"; "Rename".

Yeah, that wasn't fixed in the beta, but I fixed it already since then.

**Comment by nmaier** [comment]
I pushed a change for the translate website (you might need to force-refresh the page). It now shows an unchanged count and yellow checkmarks instead of green ones for unchanged stuff.

Still unchanged is, but probably shouldn't be:
`prefs.title`, `reset`, `select.title` and maybe the `key-` ones.

Not translated:
`renamer-info`

**Comment by dewuer** [comment]
I can see the change on the website, now.
Sorry for still missing parts.

> Still unchanged is, but probably shouldn't be:
> prefs.title, reset, select.title and maybe the key- ones.

prefs.title - changed
reset - let's leave it - it is the same word in polish
select.title - changed
key- - should leave them as they are the same on keyboard we use (US layout)

> Not translated:
> renamer-info

True, but I had no idea what it exactly means atm, so I thought I better leave it for now.
If you can give more details about this I can edit that too, not a problem - just wanted to be sure and give proper translation here.

Latest version here:
[messages.zip](https://github.com/downthemall/downthemall/files/3554377/messages.zip)

P.S. Just wanted to add that I was waiting so long for that version of DownThemAll! (WE) - thank you.

**Comment by nmaier** [comment]
It is displayed when you click the mask button and it shows the tooltip.
It essentially means that when e.g. you have a `*subdirs*` which e.g. could be `/some/path`, then prepending `flat` to it i.e. `*flatsubdirs*` it will do `-some-path` replacing the slashes, to avoid creating many sub-directories. that's why the word `flat` shouldn't be replaced in that string
