### ISSUE TITLE
New version of DTA downloads files that already exist even when "Skip" option is selected.

### ISSUE THREAD

**Issue by obkb** [downthemall/downthemall#40]
DTA version 3.0.2 (updated 2 Sept. 2016), Firefox version 47.0.1, Windows 7 Home Premium

I have configured DTA to skip a file in the download list if it already exists. Previous versions would check to see if a file existed BEFORE downloading it.

The current version downloads a file even if it already exists, then deletes it (the file it just downloaded). This wastes both time and bandwidth (especially for people with slow internet connections.

1. Select a file from a website for downloading and download it. Since your internet connection is probably much faster than mine, you will need to select a large file.
2. Repeat step 1 with the same file. Note that DTA now downloads the entire file before marking it as "skipped."

See the attached screenshot, part of an Explorer window. It shows that I downloaded a file on September 1. It is now September 2, and DTA is downloading the same file.

**Comment by nmaier** [comment]
This was fixed in 3.0.5 already

**Comment by Beautyfield** [comment]
I have 3.0.8 installed and i can confirm the bug is still there.
